### ISSUE TITLE
Cancelling the XHR request

### ISSUE THREAD

**Issue by skosch** [SoAanyip/React-FileUpload#10]
Hey,

loving this component! 多謝！

I'm potentially uploading pretty large files, and I'd like to be able to stop the upload somehow.

Do you think you could provide a way to `abort` the XHR request? I realize right now it's encapsuled in `commonUpload`, so we'd either have to pull it outside of that function (so I can call `this.refs.uploader.abort()`), or maybe we could at least provide a workaround by, say, aborting if the user returns true (or false?) from within the `progress` callback? What do you think?

**Comment by SoAanyip** [comment]
@skosch 
Thanks for your appreciation :smile:! I have thinking about this function. This should be added in the next version. But I am affraid I can not finish this in a few days because I am in an closed company training!
I think it is better to provide a function like  this.refs.upload.abort(), then you would not have to check in every progress. Right?

**Comment by skosch** [comment]
No worries!

A separate function would be preferable, I agree. Also would have to abort IE requests if there are any ... 

I'll only need it in a few weeks from now anyway. Worst case I'll try my hand at a PR then, but if you can come up with a solution before then all the better! :)

**Comment by SoAanyip** [comment]
@skosch
I will be back in 10 days and I think it will be done in 2 weeks. If you need this before that time, PR is welcomed. :smile:

**Comment by SoAanyip** [comment]
@skosch 
Now `abort` works in modern browsers.
Please check if there are any problems. And I will try to make it work in ie9- later.

**Comment by skosch** [comment]
Thank you! Keeping a list of requests around for aborting them is a sane way of going about things, I think :+1:

I haven't encountered errors so far; if I run into problems I'll open another issue. Thanks again!
