### ISSUE TITLE
Order of the fields..

### ISSUE THREAD

**Issue by Pritoj** [SoAanyip/React-FileUpload#11]
Hey @SoAanyip ,
Love this component! I'm using it to upload files to a sailsjs server.

Salis uses [Skipper](https://github.com/balderdashy/skipper) as a body parser. Skipper has [hhis quirky bug](https://github.com/balderdashy/skipper#text-parameters) where it will ignore all text fields sent after the file upload. This gives a bit buggy behaviour.

I propose a simple ordering option which tells the component which ones to append first. I'd be happy to add this to it. What are your thoughts on this?

**Comment by SoAanyip** [comment]
@Pritoj
Thanks for your suggestion! I haven't thought about this yet, if you are willing to do a PR, it will be welcomed. Or I will try to add this later :smile:.
