### ISSUE TITLE
Is there a full example?

### ISSUE THREAD

**Issue by omidfi** [SoAanyip/React-FileUpload#12]
Hi,

Thanks for the great component. Is there a full working example to check out? Or a demo?

Omid

**Comment by SoAanyip** [comment]
@omidfi 
I should let the example more clear, yes. Will be update soon! :smile:

**Comment by SoAanyip** [comment]
@omidfi 
I added a working example in readme. I`d like to add a demo, but I am afraid I don`t have much time to do this in a short time...

**Comment by omidfi** [comment]
Thank you for the example :)
