### ISSUE TITLE
能够做到选择文件之后继续添加文件吗

### ISSUE THREAD

**Issue by zhuscat** [SoAanyip/React-FileUpload#14]
能够做到选择文件之后继续添加文件吗？
目前貌似没有这个接口。

**Comment by SoAanyip** [comment]
@zhuscat 
在现代浏览器情况下，由于可以直接获取文件对象，所以我自己在使用的时候一般是通过变量保存了用户已选的文件数组，用户再次选择的时候便可以合并两次数组的方式来实现继续添加。

**Comment by zhuscat** [comment]
好的，谢谢

**Comment by zhuscat** [comment]
但是用该组件如何去实现这种功能呢？我发现回调里面的 files 是 FileList 类型的，其只有一个方法 item，length为只读。不知道该怎么做，请指教。

**Comment by SoAanyip** [comment]
@zhuscat 
Filelist 是可以遍历的，我等下给你一个例子！

**Comment by zhuscat** [comment]
@SoAanyip 感谢！！！去看了一下 `File` 和 `FormData` 的知识，大概明白如何做了。但我还有一个疑惑，就是能够使用你这个组件的 API 实现该功能吗？貌似只有在生命周期里能拿到文件”数组“，难道是通过修改该”数组“？

**Comment by SoAanyip** [comment]
@zhuscat 
在生命周期里能够拿到这个数组就可以保存起来了，类似于

```
let fileArray = []

chooseFile(files) {
  //files就是用户选择的文件的FileList对象
  Object.keys(files).map(key=>{
    if(key === 'length') return
    fileArray.push(files[key])
  })
  //这时便可以以数组方式保存文件了
}
```

**Comment by zhuscat** [comment]
@SoAanyip 懂了！谢谢！
