### ISSUE TITLE
How I can track progress for each file

### ISSUE THREAD

**Issue by viktortomilin** [SoAanyip/React-FileUpload#15]
Hi, dude. I use this component for uploading pictures on my project. So, I faced with issue. I not see how I can track progress for each file if user uploaded multiple files. Because I should know some identification for each file which been uploaded. But I can't find example for it.

Can you help me with it? Maybe some example or something else?

Thx.

**Comment by SoAanyip** [comment]
@viktortomilin
I am not sure xhr.onprogress could response for each file that been uploaded in one xhr or not. The progress in the uploading function is just about the xhr. Maybe you could help me about this?
