### ISSUE TITLE
上传中文文件名的时候会有问题，PHP的_FILES数组为空

### ISSUE THREAD

**Issue by madwolfcrazy** [SoAanyip/React-FileUpload#17]
上传中文文件名的文件时候会有问题，PHP的$_FILES数组为空
用 fileFieldName 这个属性去处理一下就好了，但不知道这应该是哪部分的锅

**Comment by SoAanyip** [comment]
@madwolfcrazy 
不知道是不是因为需要进行encodeURIComponent? 因为我没在PHP环境进行过测试，试试看：

```
fileFieldName(file) {
  return encodeURIComponent(file.name)
},
```
