### ISSUE TITLE
change ref to fb's offcial function syntax?

### ISSUE THREAD

**Issue by wubocong** [SoAanyip/React-FileUpload#18]
[https://facebook.github.io/react/docs/more-about-refs.html](url)
"ref=" syntax is now deprecated

**Comment by SoAanyip** [comment]
@wubocong 

> Although string refs are not deprecated, they are considered legacy, and will likely be deprecated at some point in the future. Callback refs are preferred.

I will change refs to callback functions. Thanks!

**Comment by wubocong** [comment]
Thx! However, I can not wait to complete my work, so I refactored your code to a new repository [react-upload-file](https://github.com/wubocong/react-upload-file). Hope you can appreciate!

**Comment by fremfi** [comment]
is this done? because the example wasn't updated
