### ISSUE TITLE
support arrow function

### ISSUE THREAD

**Issue by wubocong** [SoAanyip/React-FileUpload#19]
`chooseFile: (files) => {
      this.state.files = files;
      this.props.creatingFiles();
      return true;
    }`
when I did this, I couldn't get the files' list, I guess possibly the problem of **this** pointer

**Comment by Pritoj** [comment]
This is not an arrow function problem but a problem with binding.

I think this should work...

```
var chooseFile = (files) => { this.state.files = files; this.props.creatingFiles(); return true; };

var options = {
chooseFile : chooseFile.bind(this);
}
```

**Comment by wubocong** [comment]
@Pritoj No, that's not the point, I find it difficult to handle state using this component because it doesn't have a parent pointer.

**Comment by SoAanyip** [comment]
@wubocong I tried and got `this` as the React component:

```
<FileUpload options={{
  baseUrl: '/upload',
  chooseFile:(file)=> {
    console.log(this)
  }
}}>
```

Can I know what you got by logging `this` ?

**Comment by wubocong** [comment]
I found this problem if using es5 function incorrectly. Besides I figure out that the Filelist object can't be enumerable, so I manually reassembled it and refactored your code. I have created a new repository [react-upload-file](https://github.com/wubocong/react-upload-file). Comments welcomed!
