### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by cybertriton** [SoAanyip/React-FileUpload#5]
**Update:**  This is because the FileUpload component doesn't use the "name" (aka "fileFieldName") provided by the client as the key of the uploaded file. 

It is a server issue. The server side expects FormData with
I am trying to use this component bu have got a "400" error. Don't know where the issue is but the stack trace is as follows.

commonUpload	@	FileUpload.js:474
commonChange	@	FileUpload.js:251
LinkedValueUtils.executeOnChange	@	LinkedValueUtils.js:129
_handleChange	@	ReactDOMInput.js:106
ReactErrorUtils.invokeGuardedCallback	@	ReactErrorUtils.js:71
executeDispatch	@	EventPluginUtils.js:79
executeDispatchesInOrder	@	EventPluginUtils.js:102
executeDispatchesAndRelease	@	EventPluginHub.js:43
executeDispatchesAndReleaseTopLevel	@	EventPluginHub.js:54
forEachAccumulated	@	forEachAccumulated.js:23
EventPluginHub.processEventQueue	@	EventPluginHub.js:259
runEventQueueInBatch	@	ReactEventEmitterMixin.js:18
ReactEventEmitterMixin.handleTopLevel	@	ReactEventEmitterMixin.js:34
handleTopLevelWithoutPath	@	ReactEventListener.js:93
handleTopLevelImpl	@	ReactEventListener.js:73
Mixin.perform	@	Transaction.js:136
ReactDefaultBatchingStrategy.batchedUpdates	@	ReactDefaultBatchingStrategy.js:62
batchedUpdates	@	ReactUpdates.js:94
ReactEventListener.dispatchEvent	@	ReactEventListener.js:204

**Comment by SoAanyip** [comment]
My bad because I did not describe the property `fileFieldName` right.
If a file is like `{name: 'foo.txt', lastModified:12345678901, somePropYouAdd: 'aaaa'}` ,
then the options could be `{fileFIeldName: 'somePropYouAdd'}` ,and FormData would append('aaaa',file).

Hope you would show your using case ,and I will try to fix it.

**Comment by bojoyzhou** [comment]
fileFieldName 挺不科学的，
比如后台的接口接受$_FILES['file']来获取上传的文件，所以想当然的就会把fileFieldName赋值成‘file’，但是你这个是从File对象上面读取'file'的值，不是很合理

**Comment by SoAanyip** [comment]
@bojoyzhou 是的，我也觉得这个属性挺迷惑的。现在v2.1.0更新了这个属性，接受string时为直接使用此string，接受func时才使用返回值。
```

fileFieldName: 'file'
//or
fileFieldName(file) {
  return file.name
}
```

感谢反馈:smile:
