### ISSUE TITLE
400L: _this3.fileFieldName 是一个属性并且值是false，你在这里当方法调用，并且你的changeLog说有说2.1.0这个特性。但是报错。fileFieldName is not a function

### ISSUE THREAD

**Issue by openwings** [SoAanyip/React-FileUpload#7]
```
var file = _this3.files[key];
var fileFieldName = _this3.fileFieldName(file);
formData.append(fileFieldName, file);
```
触发条件：
<FileUpload options={options}>
<a ref="chooseAndUpload">选择上传</a>
</FileUpload>

**Comment by SoAanyip** [comment]
@openwings 我在组件中有对属性进行PropTypes验证，如果你是这样填写参数：

```
fileFieldName: false
```

那么在控制台应该可以看到如下的警告：

> Warning: Failed propType: Invalid prop `options.fileFieldName` supplied to `FileUpload`. Check the render method of `Hello`.

如果我理解错了你的调用方式或者没有看到控制台警告，请告诉我:smile:。

**Comment by SoAanyip** [comment]
很抱歉是我的疏忽，bug fixed！
