### ISSUE TITLE
如果baseUrl是一个跨域的url，该如何设置？

### ISSUE THREAD

**Issue by gejiawen** [SoAanyip/React-FileUpload#9]
如题。

是否有设置上传接口调用时配置header的入口？

**Comment by SoAanyip** [comment]
@gejiawen 之前还没有考虑到跨域的设置，
如果要添加相应的功能，你觉得会需要暴露xhr，还是允许设置头信息比较好？

**Comment by gejiawen** [comment]
设置头信息应该会相对简单一些吧。

**Comment by SoAanyip** [comment]
现在添加了两个可选属性， `withCredentials` 和 `requestHeaders` ，均与xhr的表现一致。后者key value作为setRequestHeader的key value。

**Comment by gejiawen** [comment]
@SoAanyip 你的main文件不是根据src/下的源文件compress得到的？我看你直接在里面修改了？

**Comment by SoAanyip** [comment]
@gejiawen 是webpack过babel跟es6 loader出来的
